# Generated by Django 2.2.5 on 2019-09-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
    ]
