# Generated by Django 2.2.5 on 2019-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190910_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='Date',
            field=models.CharField(blank=True, max_length=255, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='post',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='post',
            name='No',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='Score',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='スコア'),
        ),
        migrations.AddField(
            model_name='post',
            name='Sex',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='post',
            name='TOEIC',
            field=models.CharField(blank=True, max_length=255, verbose_name='TOEIC'),
        ),
    ]
