# Generated by Django 2.2.5 on 2019-09-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190910_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Name',
        ),
        migrations.AddField(
            model_name='post',
            name='Sentence',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='発話'),
        ),
    ]
